Documentation:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

##################### Metrics ##################################

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

##################### Lint ##################################

